module.exports = {
    "sha": "6d1fd68d5d273f6c46113f5843731131ad226d64",
    "name": "numenta/experiments",
    "target_url": "https://travis-ci.org/numenta/experiments/builds/21483993",
    "description": "NuPIC Status: All validations passed (Contributor Validator, Travis Validator)",
    "state": "success",
    "branches": [],
    "commit": {
        "sha": "6d1fd68d5d273f6c46113f5843731131ad226d64",
        "commit": {
            "author": {
                "name": "Matthew Taylor",
                "email": "rhyolight@gmail.com",
                "date": "2014-03-25T04:38:48Z"
            },
            "committer": {
                "name": "Matthew Taylor",
                "email": "rhyolight@gmail.com",
                "date": "2014-03-25T04:38:48Z"
            },
            "message": "Update README.md",
            "tree": {
                "sha": "067e3d6dd8e046735031285b633fe7c20c4b2b27",
                "url": "https://api.github.com/repos/numenta/experiments/git/trees/067e3d6dd8e046735031285b633fe7c20c4b2b27"
            },
            "url": "https://api.github.com/repos/numenta/experiments/git/commits/6d1fd68d5d273f6c46113f5843731131ad226d64",
            "comment_count": 0
        },
        "url": "https://api.github.com/repos/numenta/experiments/commits/6d1fd68d5d273f6c46113f5843731131ad226d64",
        "html_url": "https://github.com/numenta/experiments/commit/6d1fd68d5d273f6c46113f5843731131ad226d64",
        "comments_url": "https://api.github.com/repos/numenta/experiments/commits/6d1fd68d5d273f6c46113f5843731131ad226d64/comments",
        "author": {
            "login": "rhyolight",
            "id": 15566,
            "avatar_url": "https://avatars.githubusercontent.com/u/15566?",
            "gravatar_id": "92b95d73c678f23c6060e63bff3dbcbd",
            "url": "https://api.github.com/users/rhyolight",
            "html_url": "https://github.com/rhyolight",
            "followers_url": "https://api.github.com/users/rhyolight/followers",
            "following_url": "https://api.github.com/users/rhyolight/following{/other_user}",
            "gists_url": "https://api.github.com/users/rhyolight/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rhyolight/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rhyolight/subscriptions",
            "organizations_url": "https://api.github.com/users/rhyolight/orgs",
            "repos_url": "https://api.github.com/users/rhyolight/repos",
            "events_url": "https://api.github.com/users/rhyolight/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rhyolight/received_events",
            "type": "User",
            "site_admin": false
        },
        "committer": {
            "login": "rhyolight",
            "id": 15566,
            "avatar_url": "https://avatars.githubusercontent.com/u/15566?",
            "gravatar_id": "92b95d73c678f23c6060e63bff3dbcbd",
            "url": "https://api.github.com/users/rhyolight",
            "html_url": "https://github.com/rhyolight",
            "followers_url": "https://api.github.com/users/rhyolight/followers",
            "following_url": "https://api.github.com/users/rhyolight/following{/other_user}",
            "gists_url": "https://api.github.com/users/rhyolight/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rhyolight/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rhyolight/subscriptions",
            "organizations_url": "https://api.github.com/users/rhyolight/orgs",
            "repos_url": "https://api.github.com/users/rhyolight/repos",
            "events_url": "https://api.github.com/users/rhyolight/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rhyolight/received_events",
            "type": "User",
            "site_admin": false
        },
        "parents": [{
            "sha": "9594d18d57ca80cdb66aacce2475eebca61c1593",
            "url": "https://api.github.com/repos/numenta/experiments/commits/9594d18d57ca80cdb66aacce2475eebca61c1593",
            "html_url": "https://github.com/numenta/experiments/commit/9594d18d57ca80cdb66aacce2475eebca61c1593"
        }]
    },
    "repository": {
        "id": 10708772,
        "name": "experiments",
        "full_name": "numenta/experiments",
        "owner": {
            "login": "numenta",
            "id": 1039191,
            "avatar_url": "https://avatars.githubusercontent.com/u/1039191?",
            "gravatar_id": "faac04630eba5ec1aeda8bcbca3ff018",
            "url": "https://api.github.com/users/numenta",
            "html_url": "https://github.com/numenta",
            "followers_url": "https://api.github.com/users/numenta/followers",
            "following_url": "https://api.github.com/users/numenta/following{/other_user}",
            "gists_url": "https://api.github.com/users/numenta/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/numenta/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/numenta/subscriptions",
            "organizations_url": "https://api.github.com/users/numenta/orgs",
            "repos_url": "https://api.github.com/users/numenta/repos",
            "events_url": "https://api.github.com/users/numenta/events{/privacy}",
            "received_events_url": "https://api.github.com/users/numenta/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/numenta/experiments",
        "description": "A junk repo for experimenting with git flows and toolins",
        "fork": false,
        "url": "https://api.github.com/repos/numenta/experiments",
        "forks_url": "https://api.github.com/repos/numenta/experiments/forks",
        "keys_url": "https://api.github.com/repos/numenta/experiments/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/numenta/experiments/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/numenta/experiments/teams",
        "hooks_url": "https://api.github.com/repos/numenta/experiments/hooks",
        "issue_events_url": "https://api.github.com/repos/numenta/experiments/issues/events{/number}",
        "events_url": "https://api.github.com/repos/numenta/experiments/events",
        "assignees_url": "https://api.github.com/repos/numenta/experiments/assignees{/user}",
        "branches_url": "https://api.github.com/repos/numenta/experiments/branches{/branch}",
        "tags_url": "https://api.github.com/repos/numenta/experiments/tags",
        "blobs_url": "https://api.github.com/repos/numenta/experiments/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/numenta/experiments/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/numenta/experiments/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/numenta/experiments/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/numenta/experiments/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/numenta/experiments/languages",
        "stargazers_url": "https://api.github.com/repos/numenta/experiments/stargazers",
        "contributors_url": "https://api.github.com/repos/numenta/experiments/contributors",
        "subscribers_url": "https://api.github.com/repos/numenta/experiments/subscribers",
        "subscription_url": "https://api.github.com/repos/numenta/experiments/subscription",
        "commits_url": "https://api.github.com/repos/numenta/experiments/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/numenta/experiments/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/numenta/experiments/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/numenta/experiments/issues/comments/{number}",
        "contents_url": "https://api.github.com/repos/numenta/experiments/contents/{+path}",
        "compare_url": "https://api.github.com/repos/numenta/experiments/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/numenta/experiments/merges",
        "archive_url": "https://api.github.com/repos/numenta/experiments/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/numenta/experiments/downloads",
        "issues_url": "https://api.github.com/repos/numenta/experiments/issues{/number}",
        "pulls_url": "https://api.github.com/repos/numenta/experiments/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/numenta/experiments/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/numenta/experiments/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/numenta/experiments/labels{/name}",
        "releases_url": "https://api.github.com/repos/numenta/experiments/releases{/id}",
        "created_at": "2013-06-15T16:23:06Z",
        "updated_at": "2014-03-25T04:30:09Z",
        "pushed_at": "2014-03-25T04:30:07Z",
        "git_url": "git://github.com/numenta/experiments.git",
        "ssh_url": "git@github.com:numenta/experiments.git",
        "clone_url": "https://github.com/numenta/experiments.git",
        "svn_url": "https://github.com/numenta/experiments",
        "homepage": null,
        "size": 344,
        "stargazers_count": 2,
        "watchers_count": 2,
        "language": null,
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": true,
        "forks_count": 4,
        "mirror_url": null,
        "open_issues_count": 7,
        "forks": 4,
        "open_issues": 7,
        "watchers": 2,
        "default_branch": "master",
        "master_branch": "master"
    },
    "sender": {
        "login": "numenta-ci",
        "id": 4650657,
        "avatar_url": "https://avatars.githubusercontent.com/u/4650657?",
        "gravatar_id": "00d730d6342f80cdad84a37a176d0c49",
        "url": "https://api.github.com/users/numenta-ci",
        "html_url": "https://github.com/numenta-ci",
        "followers_url": "https://api.github.com/users/numenta-ci/followers",
        "following_url": "https://api.github.com/users/numenta-ci/following{/other_user}",
        "gists_url": "https://api.github.com/users/numenta-ci/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/numenta-ci/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/numenta-ci/subscriptions",
        "organizations_url": "https://api.github.com/users/numenta-ci/orgs",
        "repos_url": "https://api.github.com/users/numenta-ci/repos",
        "events_url": "https://api.github.com/users/numenta-ci/events{/privacy}",
        "received_events_url": "https://api.github.com/users/numenta-ci/received_events",
        "type": "User",
        "site_admin": false
    }
};